<?php

DEFINE('IP_MASTER',"186.4.219.172");
DEFINE('EMPRESA_MASTER',"LISTA_EMPRESAS");
DEFINE('BASE_ACTIVOS',"ACTIVOS_DESARROLLO");
DEFINE('BASE_SALUD',"SALUD_DESARROLLO");
DEFINE('BASE_INNOVERS',"DB_INNOVERS");
DEFINE('BASE_ACCESOS',"");
DEFINE('NUM_TABLA_ACCESOS',10);

?>